image: node:boron
services:
  - mongo:latest
  - redis:latest

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --app=lvconnect --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
  environment:
    name: staging
    url: https://lvconnect.herokuapp.com
  tags:
    - node

deploy_production:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh linkvalue@62.4.5.247 "rm -rf lvconnect && git clone git@gitlab.com:LinkValue/Lab/LvConnect.git lvconnect && cd lvconnect && yarn install"
  only:
    - tags
  when: manual
  environment:
    name: production
    url: https://lvconnect.link-value.fr

