image: node:boron

stages:
  - test
  - deploy

lint_and_test:
  stage: test
  script:
    - yarn
    - yarn lint
  tags:
    - node

deploy_staging:
  image: tmaier/dpl:latest
  stage: deploy
  script:
    - dpl --provider=heroku --app=cracra-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
  except:
    - tags
  environment:
    name: staging
    url: https://lvconnect.herokuapp.com
  tags:
    - node

deploy_production:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh linkvalue@62.4.5.247 "rm -rf lvconnect && git clone git@gitlab.com:LinkValue/Lab/LvConnect/LvConnect.git lvconnect && cd lvconnect && yarn install && cp ~/local.js config/ && pm2 restart all"
  only:
    - tags
  when: manual
  environment:
    name: production
    url: https://lvconnect.link-value.fr

